image: Ubuntu1804  # образ для сборки

stack: node 18  # окружение

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

install:
  - yarn install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

test_script:
  - npm run lint  # скрипт линтера

build_script:
  - npm run build   # команда сборки

